# Generated by Django 4.1.5 on 2023-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdata',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
