# Generated by Django 4.1.5 on 2023-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_workoutdata_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdata',
            name='cals_burned',
            field=models.FloatField(null=True),
        ),
    ]
