# Generated by Django 4.1.5 on 2023-01-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_workoutdata_cals_burned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutdata',
            old_name='cals_burned',
            new_name='active_energy_burned',
        ),
    ]
