# Generated by Django 4.1.5 on 2023-01-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_workout_delete_workoutdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='WorkoutData',
        ),
    ]
