# Generated by Django 4.1.5 on 2023-01-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_workout_workoutdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutdata',
            old_name='calories_burned',
            new_name='cals_burned',
        ),
    ]
