# Generated by Django 4.1.5 on 2023-01-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_calories_burned_workoutdata_cals_burned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutdata',
            old_name='cals_burned',
            new_name='calories_burned',
        ),
    ]
