# Generated by Django 4.1.5 on 2023-01-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_rename_cals_burned_workoutdata_calories_burned'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutData',
            new_name='RunningWorkoutData',
        ),
    ]
