# Generated by Django 4.1.5 on 2023-01-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_workoutdata_runningworkoutdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningworkoutdata',
            old_name='calories_burned',
            new_name='cals_burned',
        ),
    ]
