# Generated by Django 4.1.5 on 2023-03-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_calories_burned_runningworkoutdata_cals_burned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningworkoutdata',
            options={'ordering': ['-start_date']},
        ),
        migrations.CreateModel(
            name='HeartRateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.runningworkoutdata')),
            ],
        ),
    ]
