# Generated by Django 4.1.5 on 2023-03-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_runningworkoutdata_options_heartratedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartratedata',
            options={'ordering': ['-workout__start_date']},
        ),
        migrations.RenameField(
            model_name='heartratedata',
            old_name='value',
            new_name='heart_rate',
        ),
    ]
