# Generated by Django 4.1.5 on 2023-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_heartratedata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartratedata',
            name='heart_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
