# Generated by Django 4.1.5 on 2023-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_heartratedata_options_heartratedata_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartratedata',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='runningworkoutdata',
            name='heart_rate_data',
        ),
        migrations.AlterField(
            model_name='heartratedata',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='heartratedata',
            name='heart_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heartratedata',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
