# Generated by Django 4.1.5 on 2023-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_remove_heartratedata_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartratedata',
            name='heart_rate',
            field=models.FloatField(),
        ),
    ]
