# Generated by Django 4.1.5 on 2023-03-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_heartratedata_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartratedata',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_data', to='application.runningworkoutdata'),
        ),
    ]
