# Generated by Django 4.1.5 on 2023-07-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_heartratedata_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningworkoutdata',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
