# Generated by Django 4.1.5 on 2023-07-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_runningworkoutdata_duration'),
        ('application', '0019_alter_runningworkoutdata_duration 2'),
        ('application', '0019_alter_runningworkoutdata_duration 3'),
    ]

    operations = [
    ]
