# Generated by Django 4.1.5 on 2023-07-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_merge_20230717_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepCountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_count', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_count_data', to='application.runningworkoutdata')),
            ],
        ),
    ]
