# Generated by Django 4.1.5 on 2023-07-18 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_stepcountdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.runningworkoutdata')),
            ],
            options={
                'verbose_name': 'Workout Route',
                'verbose_name_plural': 'Workout Routes',
            },
        ),
    ]
